-- FastRoute KB + Vector schema (Supabase)
-- Objetivo: sincronizar tabelas relacionais para base vetorial de RAG
-- Estrategia: outbox + extractor incremental + pgvector

create extension if not exists vector;

-- 1) Documentos canonicos da KB
create table if not exists public.kb_documents (
  id uuid primary key default gen_random_uuid(),
  source_table text not null,
  source_pk text not null,
  source_op text not null default 'UPSERT',
  analysis_id bigint,
  repo_name text,
  kind text not null,
  title text not null,
  content text not null,
  content_hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kb_documents_source_uniq unique (source_table, source_pk)
);

create index if not exists kb_documents_analysis_idx on public.kb_documents (analysis_id);
create index if not exists kb_documents_repo_idx on public.kb_documents (repo_name);
create index if not exists kb_documents_kind_idx on public.kb_documents (kind);
create index if not exists kb_documents_hash_idx on public.kb_documents (content_hash);

-- 2) Chunks com embedding (vector store no proprio Supabase)
-- Ajuste a dimensao conforme o modelo de embedding escolhido.
create table if not exists public.kb_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.kb_documents(id) on delete cascade,
  chunk_index integer not null,
  chunk_text text not null,
  chunk_hash text not null,
  token_count integer,
  embedding vector(1536) not null,
  embedding_model text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kb_chunks_doc_chunk_uniq unique (document_id, chunk_index)
);

create index if not exists kb_chunks_document_idx on public.kb_chunks (document_id);
create index if not exists kb_chunks_chunk_hash_idx on public.kb_chunks (chunk_hash);
-- Requer ANALYZE apos carga inicial para melhor recall/performance.
create index if not exists kb_chunks_embedding_cosine_idx
  on public.kb_chunks using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- 3) Outbox de mudancas para processamento incremental
create table if not exists public.kb_outbox (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_pk text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  payload jsonb not null,
  enqueued_at timestamptz not null default now(),
  processed_at timestamptz,
  attempts integer not null default 0,
  locked_at timestamptz,
  lock_owner text,
  next_retry_at timestamptz,
  last_error text
);

create index if not exists kb_outbox_pending_idx
  on public.kb_outbox (processed_at, next_retry_at, id)
  where processed_at is null;

create index if not exists kb_outbox_source_idx
  on public.kb_outbox (source_table, source_pk);

-- 4) Trigger generico para enfileirar mudancas
create or replace function public.enqueue_kb_outbox() returns trigger as $$
declare
  v_source_pk text;
  v_payload jsonb;
begin
  if TG_OP = 'DELETE' then
    v_source_pk := coalesce(old.id::text, old.change_id::text, old.testsuite_id::text, 'unknown');
    v_payload := jsonb_build_object('old', to_jsonb(old));
  else
    v_source_pk := coalesce(new.id::text, new.change_id::text, new.testsuite_id::text, 'unknown');
    v_payload := jsonb_build_object('new', to_jsonb(new));
  end if;

  insert into public.kb_outbox (source_table, source_pk, operation, payload)
  values (TG_TABLE_NAME, v_source_pk, TG_OP, v_payload);

  if TG_OP = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$ language plpgsql;

-- 5) Triggers nas tabelas de origem (ajuste nomes se seu schema diferir)
drop trigger if exists trg_kb_outbox_impact_analysis on public.impact_analysis;
create trigger trg_kb_outbox_impact_analysis
after insert or update or delete on public.impact_analysis
for each row execute function public.enqueue_kb_outbox();

drop trigger if exists trg_kb_outbox_changes_in_repo on public.changes_in_repo;
create trigger trg_kb_outbox_changes_in_repo
after insert or update or delete on public.changes_in_repo
for each row execute function public.enqueue_kb_outbox();

drop trigger if exists trg_kb_outbox_code_changes on public.code_changes;
create trigger trg_kb_outbox_code_changes
after insert or update or delete on public.code_changes
for each row execute function public.enqueue_kb_outbox();

drop trigger if exists trg_kb_outbox_testsuites on public.testsuites_for_change;
create trigger trg_kb_outbox_testsuites
after insert or update or delete on public.testsuites_for_change
for each row execute function public.enqueue_kb_outbox();

drop trigger if exists trg_kb_outbox_tests on public.tests_for_testsuite;
create trigger trg_kb_outbox_tests
after insert or update or delete on public.tests_for_testsuite
for each row execute function public.enqueue_kb_outbox();

-- 6) View para materializar documento canonico por linha relacional
-- O extractor deve ler daqui para montar kb_documents.
create or replace view public.kb_document_candidates as
select
  'impact_analysis'::text as source_table,
  ia.id::text as source_pk,
  ia.id::bigint as analysis_id,
  null::text as repo_name,
  'analysis'::text as kind,
  ('Impact Analysis #' || ia.id::text) as title,
  coalesce(ia.change_summary, '') as content,
  md5(coalesce(ia.change_summary, '')) as content_hash,
  jsonb_build_object(
    'complexity_level', ia.complexity_level,
    'created_at', ia.created_at,
    'updated_at', ia.updated_at
  ) as metadata
from public.impact_analysis ia

union all

select
  'changes_in_repo'::text as source_table,
  c.id::text as source_pk,
  ia.id::bigint as analysis_id,
  r.name as repo_name,
  'change'::text as kind,
  ('Change #' || c.id::text || ' - ' || coalesce(r.name, 'repo')) as title,
  coalesce(c.change_summary, '') as content,
  md5(coalesce(c.change_summary, '')) as content_hash,
  jsonb_build_object(
    'repo_id', c.repo_id,
    'created_at', c.created_at,
    'updated_at', c.updated_at
  ) as metadata
from public.changes_in_repo c
left join public.repos r on r.id = c.repo_id
left join lateral (
  select i.id
  from public.impact_analysis i
  where c.change_summary like ('[impact:' || i.id::text || ']%')
  order by i.id desc
  limit 1
) ia on true

union all

select
  'code_changes'::text as source_table,
  cc.id::text as source_pk,
  ia.id::bigint as analysis_id,
  r.name as repo_name,
  'code'::text as kind,
  ('Code Change #' || cc.id::text || ' - ' || coalesce(r.name, 'repo')) as title,
  coalesce(cc.code, '') as content,
  md5(coalesce(cc.code, '')) as content_hash,
  jsonb_build_object(
    'change_id', cc.change_id,
    'created_at', cc.created_at,
    'updated_at', cc.updated_at
  ) as metadata
from public.code_changes cc
left join public.changes_in_repo c on c.id = cc.change_id
left join public.repos r on r.id = c.repo_id
left join lateral (
  select i.id
  from public.impact_analysis i
  where c.change_summary like ('[impact:' || i.id::text || ']%')
  order by i.id desc
  limit 1
) ia on true

union all

select
  'testsuites_for_change'::text as source_table,
  ts.id::text as source_pk,
  ia.id::bigint as analysis_id,
  r.name as repo_name,
  'testsuite'::text as kind,
  ('Testsuite #' || ts.id::text || ' - ' || coalesce(r.name, 'repo')) as title,
  coalesce(ts.description, '') as content,
  md5(coalesce(ts.description, '')) as content_hash,
  jsonb_build_object(
    'change_id', ts.change_id,
    'created_at', ts.created_at,
    'updated_at', ts.updated_at
  ) as metadata
from public.testsuites_for_change ts
left join public.changes_in_repo c on c.id = ts.change_id
left join public.repos r on r.id = c.repo_id
left join lateral (
  select i.id
  from public.impact_analysis i
  where c.change_summary like ('[impact:' || i.id::text || ']%')
  order by i.id desc
  limit 1
) ia on true

union all

select
  'tests_for_testsuite'::text as source_table,
  t.id::text as source_pk,
  ia.id::bigint as analysis_id,
  r.name as repo_name,
  'test'::text as kind,
  ('Test #' || t.id::text || ' - ' || coalesce(r.name, 'repo')) as title,
  coalesce(t.description, '') as content,
  md5(coalesce(t.description, '')) as content_hash,
  jsonb_build_object(
    'testsuite_id', t.testsuite_id,
    'created_at', t.created_at,
    'updated_at', t.updated_at
  ) as metadata
from public.tests_for_testsuite t
left join public.testsuites_for_change ts on ts.id = t.testsuite_id
left join public.changes_in_repo c on c.id = ts.change_id
left join public.repos r on r.id = c.repo_id
left join lateral (
  select i.id
  from public.impact_analysis i
  where c.change_summary like ('[impact:' || i.id::text || ']%')
  order by i.id desc
  limit 1
) ia on true;

